from functools import total_ordering

@total_ordering
class Product:

    def __init__(self, name: str, price: float, rating: float):
        self.name = name
        self.price = price
        self.rating = rating

    # Equality based on name and price
    def __eq__(self, other: object) -> bool:
        if not isinstance(other, Product):
            return NotImplemented   # let Python handle the fallback
        return self.name == other.name and self.price == other.price

    # Ordering based on price — @total_ordering generates the rest
    def __lt__(self, other: "Product") -> bool:
        return self.price < other.price

    # Must define __hash__ whenever you define __eq__
    def __hash__(self) -> int:
        return hash((self.name, self.price))

    def __repr__(self) -> str:
        return f"Product('{self.name}', ₹{self.price}, ⭐{self.rating})"


p1 = Product("Laptop", 65000, 4.5)
p2 = Product("Phone",  45000, 4.2)
p3 = Product("Laptop", 65000, 4.5)

print(p1 == p3)        # True  — same name and price
print(p1 == p2)        # False
print(p1 > p2)         # True  — generated by @total_ordering from __lt__
print(p2 < p1)         # True

products = [p1, p2, Product("Tablet", 30000, 4.0)]
products.sort()         # works because of __lt__
print(products)

# Works as dict key and in sets because __hash__ is defined
product_set = {p1, p2, p3}
print(len(product_set))  # 2 — p1 and p3 are equal, so set deduplicates